//
//  ---- Subroutine 'back_spc' ----
//
//  decrements string pointer to get the previous space character
//  
//  used by pwrap subroutine to print a string segment to the next line
//
//

back_spc:

bsloop:
			dey				// backtrack in string to find the last space
			lda (strp),y
			cmp #$20		// space char?
			bne bsloop		// no; continue looking

gotspc:
			rts				// (strp),y now points to last space char in string

//
// ---- end Subroutine 'back_spc'							