//   Subroutine "cls.sub" 
//  
			// 
			// Fill video RAM to spaces
			// 

cls: 
			//  preserve 'x'
			txa
			pha

			ldx #$00

clear:		lda #$20		// space char
			sta $0400,x
			sta $0500,x
			sta $0600,x
			sta $06e8,x
			inx
			bne clear		// has x reached zero?
//  if not, continue in loop 

			//  restore 'x'
			pla
			tax

			rts				//  return
//  
//  
//         End Subroutine "cls.sub" 
//  

